---
# tasks file for maven_deploy
- name: Install meven
  become: yes
  become_user: root
  shell: wget http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz && tar xvf apache-maven-3.0.5-bin.tar.gz && mv apache-maven-3.0.5  /usr/local/apache-maven
- name: Check maven
  become: yes
  become_user: root
  shell: export M2_HOME=/usr/local/apache-maven && export M2=$M2_HOME/bin && export PATH=$M2:$PATH && source ~/.bashrc && mvn -version
#- name: deploy war file
#  shell: echo "Deploy from {{ war_path }}"

